### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by manudroid19** [jordigoyanes/pinturillo3#1]
Excelente app! levante un pequeño server en una raspberry para echarnos unas partidas en la cuarentena, la webapp es excelente!!!

Solo hay un bug que tira el server cada poco y hace que lo tenga que reiniciar, esta es la salida:
```
Wait 8 seconds before starting next turn
Esto es rooms length: 1
New player connected
Esto es rooms length: 1
/home/prada/pinturillo3/dist/index.js:307
    var painter = room.players.findIndex(find_player);
                       ^

TypeError: Cannot read property 'players' of undefined
    at Socket.<anonymous> (/home/prada/pinturillo3/dist/index.js:307:24)
    at Socket.emit (events.js:210:5)
    at /home/prada/pinturillo3/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pintanary@1.0.0 start: `babel src -d dist && node dist/index.js "app"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pintanary@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/prada/.npm/_logs/2020-03-17T21_56_04_028Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```
gran trabajo!!

**Comment by kikis1034** [comment]
Yo también lo tengo instalado en la raspberry. Por ahora no me ha dado ningún error. Si tengo el mismo problema reponderé a este mensaje y trato de corregirlo.
Un saludo.
